import type { InvocableEventContext } from '@moeru/eventa'
import type { ContextInit } from '@proj-airi/plugin-sdk/plugin'
import type { SkillRegistryEntry } from '@proj-airi/skills-engine'

import process from 'node:process'

import { defineInvokeEventa, defineInvokeHandler } from '@moeru/eventa'
import { definePlugin } from '@proj-airi/plugin-sdk/plugin'
import { buildSkillsContext, SkillRegistry } from '@proj-airi/skills-engine'

// ---------------------------------------------------------------------------
// Lightweight list item (avoids shipping full skill body over the wire)
// ---------------------------------------------------------------------------

export interface SkillListItem {
  id: string
  name: string
  category: string
  version: string
  description: string
  source: string
  tags: string[]
  active: boolean
}

function toListItem(entry: SkillRegistryEntry): SkillListItem {
  return {
    id: entry.skill.metadata.id,
    name: entry.skill.metadata.name,
    category: entry.skill.metadata.category,
    version: entry.skill.metadata.version,
    description: entry.skill.metadata.description,
    source: entry.skill.source,
    tags: entry.skill.metadata.tags ?? [],
    active: entry.active,
  }
}

// ---------------------------------------------------------------------------
// Protocol events — consumers import these to invoke Skills operations.
// ---------------------------------------------------------------------------

export const skillsList = defineInvokeEventa<SkillListItem[]>(
  'airi:plugin:skills:list',
)

export const skillsToggle = defineInvokeEventa<
  { id: string, active: boolean, success: boolean },
  { id: string, active: boolean }
>('airi:plugin:skills:toggle')

export const skillsGetById = defineInvokeEventa<
  SkillListItem | null,
  { id: string }
>('airi:plugin:skills:get-by-id')

/**
 * Returns the formatted system prompt text generated by `buildSkillsContext()`.
 * This is the KEY integration point that fixes the "never called" gap.
 */
export const skillsGetContext = defineInvokeEventa<string>(
  'airi:plugin:skills:context',
)

// ---------------------------------------------------------------------------
// Plugin definition
// ---------------------------------------------------------------------------

let registry: SkillRegistry | null = null

export default definePlugin('airi-plugin-skills', '0.8.4', () => ({
  async init(_ctx: ContextInit): Promise<void | false> {
    const builtinDir = process.env.AIRI_SKILLS_BUILTIN_DIR ?? './skills/builtin'
    const userDir = process.env.AIRI_SKILLS_USER_DIR ?? './skills/user'

    registry = new SkillRegistry({ builtinSkillsDir: builtinDir, userSkillsDir: userDir })

    try {
      await registry.loadAll()
    }
    catch (err) {
      console.warn('[skills-plugin] Failed to discover skills, starting with empty registry', err)
    }
  },

  async setupModules({ channels }: ContextInit): Promise<void> {
    if (!registry) {
      throw new Error('SkillRegistry not initialized — init() must succeed before setupModules()')
    }

    // ChannelHost is typed as EventContext<unknown, unknown> but the plugin-host
    // always provides EventContext<any, any> via createPluginContext at runtime.
    // Cast to satisfy defineInvokeHandler's InvocableEventContext constraint.
    const ctx = channels.host as InvocableEventContext<unknown, { raw?: unknown }>

    defineInvokeHandler(ctx, skillsList, async () => {
      return registry!.getAll().map(toListItem)
    })

    defineInvokeHandler(ctx, skillsToggle, async ({ id, active }) => {
      const success = active ? registry!.activate(id) : registry!.deactivate(id)
      return { id, active, success }
    })

    defineInvokeHandler(ctx, skillsGetById, async ({ id }) => {
      const entry = registry!.getById(id)
      return entry ? toListItem(entry) : null
    })

    defineInvokeHandler(ctx, skillsGetContext, async () => {
      const allSkills = registry!.getAll().map(e => e.skill)
      const activeSkills = registry!.getActive()
      return buildSkillsContext(allSkills, activeSkills)
    })
  },
}))
