/**
 * Six emotion states that the persona can be in.
 */
export type EmotionState = 'neutral' | 'happy' | 'caring' | 'playful' | 'worried' | 'sad'

/**
 * Input data for evaluating trigger conditions.
 * Intentionally decoupled from context-engine's ActivityContext
 * to keep persona-engine independent.
 */
export interface TriggerInput {
  /** Duration of continuous work in milliseconds */
  continuousWorkDurationMs: number
  /** Whether the user is in a fullscreen application */
  isFullscreen: boolean
  /** Name of the current foreground application */
  currentApp: string
}

/**
 * Definition of a proactive trigger condition.
 */
export interface TriggerCondition {
  /** Unique trigger ID, e.g., 'T03' */
  id: string
  /** Human-readable name, e.g., 'rest-reminder' */
  name: string
  /** Pure function that checks if this trigger's condition is met */
  check: (input: TriggerInput) => boolean
  /** Cooldown period in milliseconds before this trigger can fire again */
  cooldownMs: number
}

/**
 * Result of trigger evaluation.
 * Discriminated union: illegal states are unrepresentable.
 */
export type TriggerResult =
  | { triggered: true, triggerId: string, triggerName: string }
  | { triggered: false }

/**
 * A proactive response generated by the persona engine.
 */
export interface ProactiveResponse {
  /** The message text to display */
  message: string
  /** Current emotion state when generating this response */
  emotion: EmotionState
  /** ID of the trigger that caused this response */
  triggerId: string
}
