/**
 * Six persona emotion states managed by the xstate emotion state machine.
 */
export type PersonaEmotion = 'idle' | 'curious' | 'caring' | 'worried' | 'sleepy' | 'excited'

/**
 * Type alias so response-generator and proactive-trigger can refer to
 * emotion states without importing PersonaEmotion directly.
 * Values: idle, curious, caring, worried, sleepy, excited.
 */
export type EmotionState = PersonaEmotion

/**
 * Five stages of intimacy progression.
 */
export type IntimacyStage = 'stranger' | 'acquaintance' | 'friend' | 'closeFriend' | 'soulmate'

/**
 * Immutable state for intimacy tracking.
 */
export interface IntimacyState {
  readonly score: number
  readonly stage: IntimacyStage
}

/**
 * Types of interactions that affect intimacy score.
 */
export type IntimacyInteraction = 'conversation' | 'deepConversation'

/**
 * Definition of an intimacy stage boundary.
 */
export interface IntimacyStageBoundary {
  readonly stage: IntimacyStage
  readonly min: number
  readonly max: number
}

/**
 * Persona template defining a character's personality and behavior.
 */
export interface PersonaTemplate {
  readonly id: string
  readonly name: string
  readonly personality: string
  readonly speakingStyle: string
  readonly defaultEmotion: PersonaEmotion
}

/**
 * Valid Anima Emotion names, mirroring stage-ui Emotion enum values.
 * Kept as a string literal union to avoid a direct dependency on stage-ui.
 */
export type AnimaEmotionName = 'happy' | 'sad' | 'angry' | 'think' | 'surprised' | 'awkward' | 'question' | 'curious' | 'neutral'

/**
 * Anima Emotion payload loosely modeling stage-ui EmotionPayload.
 * name is a literal union rather than importing the Emotion enum directly
 * to keep persona-engine independent of stage-ui.
 */
export interface AnimaEmotionPayload {
  readonly name: AnimaEmotionName
  readonly intensity: number
}

/**
 * Input data for evaluating trigger conditions.
 * Intentionally decoupled from context-engine's ActivityContext
 * to keep persona-engine independent.
 */
export interface TriggerInput {
  /** Duration of continuous work in milliseconds */
  readonly continuousWorkDurationMs: number
  /** Whether the user is in a fullscreen application */
  readonly isFullscreen: boolean
  /** Name of the current foreground application */
  readonly currentApp: string
}

/**
 * Definition of a proactive trigger condition.
 */
export interface TriggerCondition {
  /** Unique trigger ID, e.g., 'T03' */
  readonly id: string
  /** Human-readable name, e.g., 'rest-reminder' */
  readonly name: string
  /** Pure function that checks if this trigger's condition is met */
  readonly check: (input: TriggerInput) => boolean
  /** Cooldown period in milliseconds before this trigger can fire again */
  readonly cooldownMs: number
}

/**
 * Result of trigger evaluation.
 * Discriminated union: illegal states are unrepresentable.
 */
export type TriggerResult
  = | { triggered: true, triggerId: string, triggerName: string }
    | { triggered: false }

/**
 * A proactive response generated by the persona engine.
 */
export interface ProactiveResponse {
  /** The message text to display */
  message: string
  /** Current emotion state when generating this response */
  emotion: EmotionState
  /** ID of the trigger that caused this response */
  triggerId: string
}
