/**
 * Six persona emotion states managed by the xstate emotion state machine.
 */
export type PersonaEmotion = 'idle' | 'curious' | 'caring' | 'worried' | 'sleepy' | 'excited'

/**
 * Type alias so response-generator and proactive-trigger can refer to
 * emotion states without importing PersonaEmotion directly.
 * Values: idle, curious, caring, worried, sleepy, excited.
 */
export type EmotionState = PersonaEmotion

/**
 * Five stages of intimacy progression.
 */
export type IntimacyStage = 'stranger' | 'acquaintance' | 'friend' | 'closeFriend' | 'soulmate'

/**
 * Immutable state for intimacy tracking.
 */
export interface IntimacyState {
  readonly score: number
  readonly stage: IntimacyStage
}

/**
 * Types of interactions that affect intimacy score.
 */
export type IntimacyInteraction = 'conversation' | 'deepConversation'

/**
 * Definition of an intimacy stage boundary.
 */
export interface IntimacyStageBoundary {
  readonly stage: IntimacyStage
  readonly min: number
  readonly max: number
}

/**
 * Persona template defining a character's personality and behavior.
 */
export interface PersonaTemplate {
  readonly id: string
  readonly name: string
  readonly personality: string
  readonly speakingStyle: string
  readonly defaultEmotion: PersonaEmotion
}

/**
 * Valid Anima Emotion names, mirroring stage-ui Emotion enum values.
 * Kept as a string literal union to avoid a direct dependency on stage-ui.
 */
export type AnimaEmotionName = 'happy' | 'sad' | 'angry' | 'think' | 'surprised' | 'awkward' | 'question' | 'curious' | 'neutral'

/**
 * Anima Emotion payload loosely modeling stage-ui EmotionPayload.
 * name is a literal union rather than importing the Emotion enum directly
 * to keep persona-engine independent of stage-ui.
 */
export interface AnimaEmotionPayload {
  readonly name: AnimaEmotionName
  readonly intensity: number
}

/**
 * Application category for detecting work/entertainment transitions.
 */
export type AppCategory = 'work' | 'entertainment' | 'other'

/**
 * Trigger priority levels determining behavior in DoNotDisturb scenarios.
 * 'critical' can bypass quiet hours.
 */
export type TriggerPriority = 'low' | 'normal' | 'high' | 'critical'

/**
 * Input data for evaluating trigger conditions.
 * Intentionally decoupled from context-engine's ActivityContext
 * to keep persona-engine independent.
 */
export interface TriggerInput {
  /** Duration of continuous work in milliseconds */
  readonly continuousWorkDurationMs: number
  /** Whether the user is in a fullscreen application */
  readonly isFullscreen: boolean
  /** Name of the current foreground application */
  readonly currentApp: string
  /** Current hour of day (0-23) */
  readonly currentHour: number
  /** Current minute (0-59) */
  readonly currentMinute: number
  /** Whether this is the first user activity detected today */
  readonly isFirstActivityToday: boolean
  /** Category of the previously active application */
  readonly previousAppCategory: AppCategory
  /** Whether there is activity data available for summary */
  readonly hasActivityData: boolean
  /** Whether today matches an important date from long-term memory */
  readonly matchedImportantDate: boolean
  /** Whether there are TODO items approaching their deadline */
  readonly hasNearDeadlineTodos: boolean
  /** Number of window switches in the last 5 minutes */
  readonly windowSwitchesInLast5Min: number
  /** Duration of previous focused session in milliseconds (for T10) */
  readonly previousFocusDurationMs: number
  /** Time since last user activity in milliseconds (for T11) */
  readonly timeSinceLastActivityMs: number
  /** Current intimacy stage with the user */
  readonly intimacyStage: IntimacyStage
}

/**
 * Definition of a proactive trigger condition.
 */
export interface TriggerCondition {
  /** Unique trigger ID, e.g., 'T03' */
  readonly id: string
  /** Human-readable name, e.g., 'rest-reminder' */
  readonly name: string
  /** Pure function that checks if this trigger's condition is met */
  readonly check: (input: TriggerInput) => boolean
  /** Cooldown period in milliseconds before this trigger can fire again */
  readonly cooldownMs: number
  /** Priority level: critical can bypass quiet hours */
  readonly priority: TriggerPriority
  /** Minimum intimacy stage required for this trigger to fire */
  readonly minIntimacy: IntimacyStage
  /** Suggested emotion state when this trigger fires */
  readonly suggestedEmotion: PersonaEmotion
}

/**
 * Result of trigger evaluation.
 * Discriminated union: illegal states are unrepresentable.
 */
export type TriggerResult
  = | { triggered: true, triggerId: string, triggerName: string, suggestedEmotion: PersonaEmotion }
    | { triggered: false }

/**
 * A proactive response generated by the persona engine.
 */
export interface ProactiveResponse {
  /** The message text to display */
  readonly message: string
  /** Current emotion state when generating this response */
  readonly emotion: EmotionState
  /** ID of the trigger that caused this response */
  readonly triggerId: string
}

/**
 * Configuration for the Do Not Disturb policy.
 */
export interface DoNotDisturbConfig {
  /** Maximum triggers allowed per hour (default: 3) */
  readonly maxPerHour: number
  /** Maximum triggers allowed per day (default: 15) */
  readonly maxPerDay: number
  /** Start of quiet hours in 24h format (default: 23) */
  readonly quietHoursStart: number
  /** End of quiet hours in 24h format (default: 7) */
  readonly quietHoursEnd: number
  /** Number of consecutive ignores before applying backoff (default: 3) */
  readonly consecutiveIgnoresForBackoff: number
  /** Cooldown multiplier applied during progressive backoff (default: 1.5) */
  readonly backoffMultiplier: number
}

/**
 * Immutable state tracking for the Do Not Disturb system.
 */
export interface DoNotDisturbState {
  /** Timestamps of recent trigger firings */
  readonly triggerTimestamps: readonly number[]
  /** Number of consecutive times the user ignored triggers */
  readonly consecutiveIgnores: number
  /** Current cooldown multiplier (1.0 = normal, increases with ignores) */
  readonly cooldownMultiplier: number
}
