/**
 * Represents a single user activity event observed by the system.
 */
export interface ActivityEvent {
  /** Unix timestamp in milliseconds */
  timestamp: number
  /** Name of the foreground application */
  appName: string
  /** Title of the active window */
  windowTitle: string
  /** Whether the app is running in fullscreen mode */
  isFullscreen: boolean
}

/**
 * Aggregated activity context derived from a series of ActivityEvents.
 */
export interface ActivityContext {
  /** Duration of continuous work in milliseconds */
  continuousWorkDurationMs: number
  /** Current foreground application name */
  currentApp: string
  /** Current active window title */
  currentWindowTitle: string
  /** Whether the current app is in fullscreen */
  isFullscreen: boolean
  /** Timestamp of the last observed activity */
  lastActivityTimestamp: number
}

/**
 * Extended activity state including recent app history and active/inactive status.
 * Extends ActivityContext with additional fields for richer monitoring output.
 */
export interface ActivityState extends ActivityContext {
  /** Whether the user is currently active */
  isActive: boolean
  /** Recently used application names (most recent first, deduplicated) */
  recentApps: string[]
}

/**
 * Combined context output from the ActivityMonitor,
 * ready to be sent as a context:update event payload.
 */
export interface ProcessedContext {
  /** User activity state */
  activity: ActivityState
  /** Optional screenshot context if available */
  screenshot?: ProcessedScreenshotContext
  /** Timestamp when this context was produced */
  timestamp: number
}

/**
 * Interface for capturing screenshots.
 * Implementations wrap platform-specific APIs (e.g., Electron desktopCapturer).
 */
export interface ScreenshotProvider {
  capture: () => Promise<Buffer>
}

/**
 * Result of a screenshot capture operation.
 */
export interface ScreenshotResult {
  /** Raw image data */
  buffer: Buffer
  /** Capture timestamp in milliseconds */
  timestamp: number
}

/**
 * Interface for Vision Language Model providers.
 * Implementations wrap specific LLM SDKs (e.g., AI SDK 6, xsAI).
 */
export interface VlmProvider {
  describeImage: (imageBuffer: Buffer) => Promise<VlmResult>
}

/**
 * Raw result from a VLM image description call.
 */
export interface VlmResult {
  /** Natural language description of what the user is doing */
  description: string
  /** Entities detected in the screenshot (apps, tools, content types) */
  entities: string[]
  /** High-level activity category (e.g., 'coding', 'browsing', 'writing') */
  activity: string
}

/**
 * Processed screenshot context after VLM understanding and pHash computation.
 * This is the final output of the screenshot pipeline.
 */
export interface ProcessedScreenshotContext {
  /** Natural language description */
  description: string
  /** Detected entities */
  entities: string[]
  /** Activity category */
  activity: string
  /** Capture timestamp in milliseconds */
  timestamp: number
  /** 64-bit perceptual hash as a binary string */
  hash: string
}

// --- Smart Generation Provider Interfaces ---

/**
 * Interface for LLM text/structured generation.
 * Implementations wrap specific LLM SDKs (e.g., Vercel AI SDK generateObject/generateText).
 */
export interface LlmProvider {
  /** Generate free-form text from a system + user prompt */
  generateText: (options: { system: string, prompt: string }) => Promise<string>
  /**
   * Generate a structured JSON response matching the described schema.
   * The `schemaDescription` is a plain-language description of expected fields;
   * the implementation decides how to enforce structure (e.g., AI SDK jsonSchema, function calling).
   */
  generateStructured: <T>(options: {
    system: string
    prompt: string
    schemaDescription: string
  }) => Promise<T>
}

/**
 * Interface for embedding text into vectors.
 * Implementations wrap specific embedding APIs (e.g., OpenAI text-embedding-3-small).
 */
export interface EmbeddingProvider {
  embed: (text: string) => Promise<number[]>
  readonly dimension: number
}

// --- Smart Generation Output Types ---

/**
 * A single activity entry in a daily summary breakdown.
 */
export interface ActivityBreakdownEntry {
  app: string
  durationMs: number
  description: string
}

/**
 * Daily summary report generated by ReportGenerator.
 */
export interface DailySummary {
  date: string
  highlights: string[]
  activityBreakdown: ActivityBreakdownEntry[]
  totalWorkDurationMs: number
  personalNote: string
}

/**
 * Output from the SmartTip module.
 */
export interface SmartTipResult {
  headline: string
  note: string
  kind: 'alarm' | 'ping' | 'reminder'
  urgency: 'immediate' | 'soon' | 'later'
}

/**
 * A single todo suggestion extracted by SmartTodo.
 */
export interface TodoSuggestion {
  title: string
  reason: string
}

/**
 * Output from the SmartTodo module.
 */
export interface SmartTodoResult {
  suggestions: TodoSuggestion[]
}

/**
 * Persona template for character-styled output.
 * Mirrors PersonaTemplate from persona-engine to avoid cross-package dependency.
 */
export interface PersonaConfig {
  readonly name: string
  readonly personality: string
  readonly speakingStyle: string
}
